# /etc/puppetlabs/puppet/hiera.yaml
:backends:
  - yaml
:hierarchy:
  - node/%{::clientcert}
  - role/%{::role}
  - location/%{::datacenter}
  - common
:yaml:
  :datadir: /etc/puppetlabs/code/environments/%{::environment}/hieradata

